// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbl9irKgdRuq_lNvMZ-_0oV8SCX3LOzeI',
    appId: '1:123475107575:web:64e149db55bc1d2b3b3df2',
    messagingSenderId: '123475107575',
    projectId: 'nutricareapp-57d9e',
    authDomain: 'nutricareapp-57d9e.firebaseapp.com',
    storageBucket: 'nutricareapp-57d9e.firebasestorage.app',
    measurementId: 'G-YWFSE245SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTNbS1vwxc0LZsnorwBNZDjOXoVjpPRk4',
    appId: '1:123475107575:android:2cefb75a4eb6d63f3b3df2',
    messagingSenderId: '123475107575',
    projectId: 'nutricareapp-57d9e',
    storageBucket: 'nutricareapp-57d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRUE-VRDqm6a0Oye9kL14nAZQY70tqeq0',
    appId: '1:123475107575:ios:1d1246e7aa9eaa853b3df2',
    messagingSenderId: '123475107575',
    projectId: 'nutricareapp-57d9e',
    storageBucket: 'nutricareapp-57d9e.firebasestorage.app',
    iosBundleId: 'com.example.nutricareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRUE-VRDqm6a0Oye9kL14nAZQY70tqeq0',
    appId: '1:123475107575:ios:1d1246e7aa9eaa853b3df2',
    messagingSenderId: '123475107575',
    projectId: 'nutricareapp-57d9e',
    storageBucket: 'nutricareapp-57d9e.firebasestorage.app',
    iosBundleId: 'com.example.nutricareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbl9irKgdRuq_lNvMZ-_0oV8SCX3LOzeI',
    appId: '1:123475107575:web:069b77fcfaeca1f73b3df2',
    messagingSenderId: '123475107575',
    projectId: 'nutricareapp-57d9e',
    authDomain: 'nutricareapp-57d9e.firebaseapp.com',
    storageBucket: 'nutricareapp-57d9e.firebasestorage.app',
    measurementId: 'G-QBT28P4NJF',
  );
}
