name: nutricare_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.10
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fl_chart: ^1.0.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_database: ^11.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Shrikhand
      fonts:
        - asset: assets/fonts/Shrikhand-Regular.ttf

  assets:
    - assets/images/logo.png
    - assets/images/arrow_down_icon.png
    - assets/images/profil.png
    - assets/images/anak_sekolah.png
    - assets/images/balita.png
    - assets/images/ibu_hamil.png

  uses-material-design: true
